export interface GISPoint {
    id: string;
    name: string;
    lat: number;
    lon: number;
    type: 'river' | 'dam' | 'irrigation' | 'industrial' | 'ecology' | 'basin' | 'institute' | 'treatment' | 'pumping';
    status: 'normal' | 'warning' | 'critical';
    value: number; // e.g., water quality index or capacity %
    description: string;
    region?: string;
    owner?: string;
    level: 'global' | 'basin' | 'object';
}

export const waterGISData: GISPoint[] = [
    // Global/Basin Level
    {
        id: 'b-01',
        name: 'Аральское море (Бассейн)',
        lat: 45.0,
        lon: 60.0,
        type: 'basin',
        status: 'critical',
        value: 12,
        description: 'Критическое высыхание. Требуется глобальная рекультивация.',
        level: 'basin'
    },
    {
        id: 'b-02',
        name: 'Бассейн реки Ганг',
        lat: 25.0,
        lon: 82.0,
        type: 'basin',
        status: 'warning',
        value: 45,
        description: 'Высокая антропогенная нагрузка.',
        level: 'basin'
    },
    // Object Level - Institutes & Companies
    {
        id: 'inst-01',
        name: 'НИИ Водных Проблем',
        lat: 55.75,
        lon: 37.61,
        type: 'institute',
        status: 'normal',
        value: 98,
        description: 'Ведущий центр исследований водных ресурсов.',
        owner: 'Civilization Protocol Partner',
        level: 'object'
    },
    // Object Level - Infrastructure
    {
        id: 'p-01',
        name: 'Насосная станция №19 (Узбекистан)',
        lat: 41.31,
        lon: 69.24,
        type: 'pumping',
        status: 'warning',
        value: 72,
        description: 'Износ оборудования 65%. Требуется замена насосов.',
        owner: 'VODPROM',
        level: 'object'
    },
    {
        id: 't-01',
        name: 'Очистной узел "Чирчик"',
        lat: 41.47,
        lon: 69.58,
        type: 'treatment',
        status: 'normal',
        value: 88,
        description: 'Модернизировано по стандартам Civilization Protocol.',
        owner: 'Civilization Protocol Core',
        level: 'object'
    },
    // Existing points updated
    {
        id: 'v-01',
        name: 'Река Волга (Россия)',
        lat: 55.75,
        lon: 37.61,
        type: 'river',
        status: 'warning',
        value: 68,
        description: 'Средний уровень загрязнения. Требуется модернизация очистных.',
        level: 'basin'
    },
    {
        id: 'n-01',
        name: 'Плотина Асуан (Египет)',
        lat: 23.97,
        lon: 32.87,
        type: 'dam',
        status: 'normal',
        value: 92,
        description: 'Высокий уровень заполнения водохранилища.',
        level: 'object'
    },
    // Дополнительные точки для глобуса
    {
        id: 'b-03',
        name: 'Бассейн реки Нил',
        lat: 30.0,
        lon: 31.0,
        type: 'basin',
        status: 'warning',
        value: 58,
        description: 'Снижение уровня воды из-за климатических изменений.',
        level: 'basin'
    },
    {
        id: 'b-04',
        name: 'Бассейн реки Амазонка',
        lat: -3.0,
        lon: -60.0,
        type: 'basin',
        status: 'normal',
        value: 85,
        description: 'Стабильное состояние, мониторинг вырубки лесов.',
        level: 'basin'
    },
    {
        id: 'b-05',
        name: 'Бассейн реки Янцзы',
        lat: 30.0,
        lon: 120.0,
        type: 'basin',
        status: 'warning',
        value: 62,
        description: 'Загрязнение промышленными отходами.',
        level: 'basin'
    },
    {
        id: 'b-06',
        name: 'Бассейн реки Миссисипи',
        lat: 35.0,
        lon: -90.0,
        type: 'basin',
        status: 'normal',
        value: 78,
        description: 'Хорошее состояние, активный мониторинг.',
        level: 'basin'
    },
    {
        id: 'v-02',
        name: 'Река Дунай',
        lat: 47.0,
        lon: 19.0,
        type: 'river',
        status: 'normal',
        value: 82,
        description: 'Международный мониторинг качества воды.',
        level: 'basin'
    },
    {
        id: 'v-03',
        name: 'Река Амударья',
        lat: 40.0,
        lon: 62.0,
        type: 'river',
        status: 'critical',
        value: 28,
        description: 'Критическое снижение уровня, высыхание.',
        level: 'basin'
    },
    {
        id: 'v-04',
        name: 'Река Сырдарья',
        lat: 44.0,
        lon: 68.0,
        type: 'river',
        status: 'warning',
        value: 45,
        description: 'Снижение уровня воды, требуется модернизация.',
        level: 'basin'
    },
    {
        id: 'p-02',
        name: 'Насосная станция №7 (Казахстан)',
        lat: 51.17,
        lon: 71.43,
        type: 'pumping',
        status: 'normal',
        value: 91,
        description: 'Модернизирована в 2024, IoT датчики активны.',
        owner: 'Civilization Protocol Core',
        level: 'object'
    },
    {
        id: 'p-03',
        name: 'Насосная станция "Алматы-Восток"',
        lat: 43.22,
        lon: 76.85,
        type: 'pumping',
        status: 'warning',
        value: 68,
        description: 'Требуется замена фильтров, износ 45%.',
        owner: 'VODPROM',
        level: 'object'
    },
    {
        id: 't-02',
        name: 'Очистной комплекс "Ташкент-Центр"',
        lat: 41.31,
        lon: 69.24,
        type: 'treatment',
        status: 'normal',
        value: 95,
        description: 'Новейшие мембранные фильтры, эффективность 98%.',
        owner: 'Civilization Protocol Core',
        level: 'object'
    },
    {
        id: 't-03',
        name: 'Очистные сооружения "Самарканд"',
        lat: 39.65,
        lon: 66.96,
        type: 'treatment',
        status: 'normal',
        value: 87,
        description: 'Модернизация завершена, подключены IoT датчики.',
        owner: 'VODPROM',
        level: 'object'
    },
    {
        id: 'inst-02',
        name: 'Институт водных проблем (Ташкент)',
        lat: 41.31,
        lon: 69.24,
        type: 'institute',
        status: 'normal',
        value: 96,
        description: 'Ведущий исследовательский центр Центральной Азии.',
        owner: 'Civilization Protocol Partner',
        level: 'object'
    },
    {
        id: 'inst-03',
        name: 'UNESCO-IHE (Нидерланды)',
        lat: 52.0,
        lon: 4.3,
        type: 'institute',
        status: 'normal',
        value: 99,
        description: 'Международный институт водного образования.',
        owner: 'Civilization Protocol Partner',
        level: 'object'
    },
    {
        id: 'n-02',
        name: 'Плотина Три ущелья (Китай)',
        lat: 30.82,
        lon: 111.0,
        type: 'dam',
        status: 'normal',
        value: 88,
        description: 'Крупнейшая ГЭС в мире, активный мониторинг.',
        level: 'object'
    },
    {
        id: 'n-03',
        name: 'Плотина Итайпу (Бразилия/Парагвай)',
        lat: -25.4,
        lon: -54.6,
        type: 'dam',
        status: 'normal',
        value: 93,
        description: 'Высокая эффективность, стабильная работа.',
        level: 'object'
    },
    {
        id: 'ind-01',
        name: 'Промышленный комплекс "Алмалык"',
        lat: 40.85,
        lon: 69.6,
        type: 'industrial',
        status: 'warning',
        value: 55,
        description: 'Требуется модернизация систем очистки сточных вод.',
        owner: 'Civilization Protocol Partner',
        level: 'object'
    },
    {
        id: 'eco-01',
        name: 'Экологический заповедник "Арал"',
        lat: 45.0,
        lon: 60.0,
        type: 'ecology',
        status: 'critical',
        value: 15,
        description: 'Программа восстановления экосистемы запущена.',
        owner: 'Civilization Protocol Core',
        level: 'object'
    },
    {
        id: 'eco-02',
        name: 'Водно-болотные угодья "Дельты Волги"',
        lat: 45.7,
        lon: 47.5,
        type: 'ecology',
        status: 'normal',
        value: 78,
        description: 'Активный мониторинг биоразнообразия.',
        owner: 'Civilization Protocol Partner',
        level: 'object'
    },
    {
        id: 'irr-01',
        name: 'Ирригационная система "Фергана"',
        lat: 40.37,
        lon: 71.78,
        type: 'irrigation',
        status: 'warning',
        value: 65,
        description: 'Модернизация каналов, снижение потерь на 30%.',
        owner: 'VODPROM',
        level: 'object'
    },
    {
        id: 'irr-02',
        name: 'Ирригационная сеть "Голодная степь"',
        lat: 40.5,
        lon: 68.8,
        type: 'irrigation',
        status: 'normal',
        value: 82,
        description: 'Эффективная система распределения воды.',
        owner: 'Civilization Protocol Core',
        level: 'object'
    },
    // =============== NEW POINTS (50+) ===============
    // EUROPE
    {
        id: 'eu-01',
        name: 'Река Рейн (Германия)',
        lat: 50.94,
        lon: 6.95,
        type: 'river',
        status: 'normal',
        value: 88,
        description: 'Международный мониторинг, высокое качество воды.',
        region: 'europe',
        level: 'basin'
    },
    {
        id: 'eu-02',
        name: 'Озеро Женева',
        lat: 46.45,
        lon: 6.58,
        type: 'ecology',
        status: 'normal',
        value: 94,
        description: 'Отличное качество воды, эталонный водоём.',
        region: 'europe',
        level: 'basin'
    },
    {
        id: 'eu-03',
        name: 'Очистные Amsterdam Water',
        lat: 52.37,
        lon: 4.89,
        type: 'treatment',
        status: 'normal',
        value: 97,
        description: 'Современные очистные сооружения, полная автоматизация.',
        region: 'europe',
        owner: 'Civilization Protocol Partner',
        level: 'object'
    },
    {
        id: 'eu-04',
        name: 'Плотина Grande Dixence (Швейцария)',
        lat: 46.08,
        lon: 7.41,
        type: 'dam',
        status: 'normal',
        value: 95,
        description: 'Самая высокая гравитационная плотина в мире.',
        region: 'europe',
        level: 'object'
    },
    {
        id: 'eu-05',
        name: 'Река Темза (Великобритания)',
        lat: 51.51,
        lon: -0.12,
        type: 'river',
        status: 'normal',
        value: 75,
        description: 'Восстановленная экосистема после очистки.',
        region: 'europe',
        level: 'basin'
    },
    // MIDDLE EAST
    {
        id: 'me-01',
        name: 'Опреснительная станция Jebel Ali (ОАЭ)',
        lat: 25.07,
        lon: 55.17,
        type: 'treatment',
        status: 'normal',
        value: 96,
        description: 'Крупнейшая опреснительная станция в мире.',
        region: 'middle_east',
        level: 'object'
    },
    {
        id: 'me-02',
        name: 'Река Тигр (Ирак)',
        lat: 33.31,
        lon: 44.36,
        type: 'river',
        status: 'warning',
        value: 52,
        description: 'Снижение уровня воды, конфликт водопользования.',
        region: 'middle_east',
        level: 'basin'
    },
    {
        id: 'me-03',
        name: 'Река Евфрат (Сирия)',
        lat: 35.93,
        lon: 39.0,
        type: 'river',
        status: 'critical',
        value: 35,
        description: 'Критическое снижение уровня, засуха.',
        region: 'middle_east',
        level: 'basin'
    },
    {
        id: 'me-04',
        name: 'Мёртвое море',
        lat: 31.5,
        lon: 35.5,
        type: 'ecology',
        status: 'critical',
        value: 22,
        description: 'Катастрофическое высыхание, уровень падает на 1м/год.',
        region: 'middle_east',
        level: 'basin'
    },
    {
        id: 'me-05',
        name: 'Плотина Ататюрк (Турция)',
        lat: 37.45,
        lon: 38.32,
        type: 'dam',
        status: 'normal',
        value: 85,
        description: 'Ключевая плотина для региона, ГЭС.',
        region: 'middle_east',
        level: 'object'
    },
    // ASIA
    {
        id: 'as-01',
        name: 'Река Меконг',
        lat: 15.0,
        lon: 105.0,
        type: 'river',
        status: 'warning',
        value: 58,
        description: 'Конфликт водопользования между 6 странами.',
        region: 'asia',
        level: 'basin'
    },
    {
        id: 'as-02',
        name: 'Озеро Байкал (Россия)',
        lat: 53.5,
        lon: 108.0,
        type: 'ecology',
        status: 'normal',
        value: 92,
        description: 'Крупнейший резервуар пресной воды в мире.',
        region: 'asia',
        level: 'basin'
    },
    {
        id: 'as-03',
        name: 'Система водоснабжения Сингапур',
        lat: 1.35,
        lon: 103.82,
        type: 'treatment',
        status: 'normal',
        value: 99,
        description: 'Передовая система NEWater, рециркуляция 40%.',
        region: 'asia',
        owner: 'Civilization Protocol Partner',
        level: 'object'
    },
    {
        id: 'as-04',
        name: 'Река Инд (Пакистан)',
        lat: 25.0,
        lon: 68.0,
        type: 'river',
        status: 'warning',
        value: 48,
        description: 'Высокая засолённость, ирригационный стресс.',
        region: 'asia',
        level: 'basin'
    },
    {
        id: 'as-05',
        name: 'Озеро Аральское море Северное',
        lat: 46.8,
        lon: 61.0,
        type: 'ecology',
        status: 'warning',
        value: 45,
        description: 'Частичное восстановление благодаря плотине Кокарал.',
        region: 'central_asia',
        level: 'basin'
    },
    {
        id: 'as-06',
        name: 'Плотина Тарбела (Пакистан)',
        lat: 34.08,
        lon: 72.7,
        type: 'dam',
        status: 'normal',
        value: 78,
        description: 'Крупнейшая земляная плотина в мире.',
        region: 'asia',
        level: 'object'
    },
    // AFRICA
    {
        id: 'af-01',
        name: 'Озеро Виктория',
        lat: -1.0,
        lon: 33.0,
        type: 'ecology',
        status: 'warning',
        value: 62,
        description: 'Загрязнение, инвазивные виды, перелов.',
        region: 'africa',
        level: 'basin'
    },
    {
        id: 'af-02',
        name: 'Река Конго',
        lat: -4.4,
        lon: 15.3,
        type: 'river',
        status: 'normal',
        value: 85,
        description: 'Второй по водности бассейн в мире.',
        region: 'africa',
        level: 'basin'
    },
    {
        id: 'af-03',
        name: 'Плотина GERD (Эфиопия)',
        lat: 11.2,
        lon: 35.1,
        type: 'dam',
        status: 'normal',
        value: 72,
        description: 'Крупнейшая ГЭС Африки, спор с Египтом.',
        region: 'africa',
        level: 'object'
    },
    {
        id: 'af-04',
        name: 'Озеро Чад',
        lat: 13.0,
        lon: 14.0,
        type: 'ecology',
        status: 'critical',
        value: 18,
        description: 'Сократилось на 90% за 50 лет.',
        region: 'africa',
        level: 'basin'
    },
    {
        id: 'af-05',
        name: 'Кейптаун Water Crisis Hub',
        lat: -33.92,
        lon: 18.42,
        type: 'treatment',
        status: 'warning',
        value: 65,
        description: 'Восстановление после кризиса "Day Zero".',
        region: 'africa',
        owner: 'Civilization Protocol Partner',
        level: 'object'
    },
    // AMERICAS
    {
        id: 'am-01',
        name: 'Великие озёра (США/Канада)',
        lat: 45.0,
        lon: -84.0,
        type: 'ecology',
        status: 'normal',
        value: 88,
        description: 'Крупнейший резервуар пресной воды в Северной Америке.',
        region: 'americas',
        level: 'basin'
    },
    {
        id: 'am-02',
        name: 'Река Колорадо',
        lat: 36.0,
        lon: -112.0,
        type: 'river',
        status: 'critical',
        value: 28,
        description: 'Критический дефицит, не доходит до океана.',
        region: 'americas',
        level: 'basin'
    },
    {
        id: 'am-03',
        name: 'Плотина Гувера (США)',
        lat: 36.01,
        lon: -114.74,
        type: 'dam',
        status: 'warning',
        value: 45,
        description: 'Рекордно низкий уровень озера Мид.',
        region: 'americas',
        level: 'object'
    },
    {
        id: 'am-04',
        name: 'Водоносный слой Огаллала (США)',
        lat: 37.0,
        lon: -101.0,
        type: 'basin',
        status: 'warning',
        value: 52,
        description: 'Истощение подземных вод для сельского хозяйства.',
        region: 'americas',
        level: 'basin'
    },
    {
        id: 'am-05',
        name: 'Река Парана (Аргентина)',
        lat: -27.0,
        lon: -58.0,
        type: 'river',
        status: 'warning',
        value: 58,
        description: 'Исторически низкий уровень воды.',
        region: 'americas',
        level: 'basin'
    },
    // CENTRAL ASIA (MORE POINTS)
    {
        id: 'ca-01',
        name: 'Токтогульское водохранилище (Кыргызстан)',
        lat: 41.77,
        lon: 72.85,
        type: 'dam',
        status: 'normal',
        value: 78,
        description: 'Ключевой регулятор для Ферганской долины.',
        region: 'central_asia',
        level: 'object'
    },
    {
        id: 'ca-02',
        name: 'Нурекская ГЭС (Таджикистан)',
        lat: 38.38,
        lon: 69.35,
        type: 'dam',
        status: 'normal',
        value: 82,
        description: 'Крупнейшая ГЭС Центральной Азии.',
        region: 'central_asia',
        level: 'object'
    },
    {
        id: 'ca-03',
        name: 'Озеро Балхаш (Казахстан)',
        lat: 46.5,
        lon: 75.0,
        type: 'ecology',
        status: 'warning',
        value: 55,
        description: 'Угроза повторения судьбы Арала.',
        region: 'central_asia',
        level: 'basin'
    },
    {
        id: 'ca-04',
        name: 'Река Или (Казахстан)',
        lat: 44.0,
        lon: 77.0,
        type: 'river',
        status: 'warning',
        value: 58,
        description: 'Снижение стока из-за забора воды в Китае.',
        region: 'central_asia',
        level: 'basin'
    },
    {
        id: 'ca-05',
        name: 'Насосная станция Каршинский каскад',
        lat: 38.86,
        lon: 65.79,
        type: 'pumping',
        status: 'warning',
        value: 62,
        description: 'Крупнейшая насосная станция в мире, требуется модернизация.',
        region: 'central_asia',
        owner: 'VODPROM',
        level: 'object'
    },
    {
        id: 'ca-06',
        name: 'Ирригационная система Хорезм',
        lat: 41.55,
        lon: 60.63,
        type: 'irrigation',
        status: 'warning',
        value: 55,
        description: 'Высокие потери воды, необходима модернизация.',
        region: 'central_asia',
        level: 'object'
    },
    {
        id: 'ca-07',
        name: 'Чарвакское водохранилище',
        lat: 41.63,
        lon: 70.02,
        type: 'dam',
        status: 'normal',
        value: 85,
        description: 'Туристический и энергетический объект.',
        region: 'central_asia',
        owner: 'Civilization Protocol Core',
        level: 'object'
    },
    {
        id: 'ca-08',
        name: 'Насосная станция Бухара',
        lat: 39.77,
        lon: 64.42,
        type: 'pumping',
        status: 'normal',
        value: 88,
        description: 'Модернизирована с IoT датчиками.',
        region: 'central_asia',
        owner: 'Civilization Protocol Core',
        level: 'object'
    },
    // INDUSTRIAL FACILITIES
    {
        id: 'ind-02',
        name: 'Металлургический завод "Караганда"',
        lat: 49.8,
        lon: 73.1,
        type: 'industrial',
        status: 'warning',
        value: 48,
        description: 'Требуется модернизация системы водоочистки.',
        region: 'central_asia',
        owner: 'Civilization Protocol Partner',
        level: 'object'
    },
    {
        id: 'ind-03',
        name: 'Нефтеперерабатывающий завод "Туркменбаши"',
        lat: 40.05,
        lon: 52.96,
        type: 'industrial',
        status: 'warning',
        value: 52,
        description: 'Загрязнение Каспийского моря, требуется мониторинг.',
        region: 'central_asia',
        level: 'object'
    },
    // RESEARCH INSTITUTES
    {
        id: 'inst-04',
        name: 'IWMI (Шри-Ланка)',
        lat: 6.9,
        lon: 79.85,
        type: 'institute',
        status: 'normal',
        value: 95,
        description: 'Международный институт управления водными ресурсами.',
        region: 'asia',
        owner: 'Civilization Protocol Partner',
        level: 'object'
    },
    {
        id: 'inst-05',
        name: 'CSIRO Water (Австралия)',
        lat: -35.28,
        lon: 149.13,
        type: 'institute',
        status: 'normal',
        value: 98,
        description: 'Ведущий исследовательский центр по водным ресурсам.',
        region: 'asia',
        owner: 'Civilization Protocol Partner',
        level: 'object'
    },
    {
        id: 'inst-06',
        name: 'Центр водных технологий (Израиль)',
        lat: 32.07,
        lon: 34.77,
        type: 'institute',
        status: 'normal',
        value: 99,
        description: 'Мировой лидер в технологиях опреснения и рециркуляции.',
        region: 'middle_east',
        owner: 'Civilization Protocol Partner',
        level: 'object'
    },
    // MORE ECOLOGICAL POINTS
    {
        id: 'eco-03',
        name: 'Национальный парк Эверглейдс (США)',
        lat: 25.29,
        lon: -80.93,
        type: 'ecology',
        status: 'warning',
        value: 62,
        description: 'Восстановление водного режима болот.',
        region: 'americas',
        level: 'object'
    },
    {
        id: 'eco-04',
        name: 'Пантанал (Бразилия)',
        lat: -17.0,
        lon: -57.0,
        type: 'ecology',
        status: 'warning',
        value: 58,
        description: 'Крупнейшее болото в мире, угроза пожаров.',
        region: 'americas',
        level: 'basin'
    },
    {
        id: 'eco-05',
        name: 'Дельта Нила (Египет)',
        lat: 31.0,
        lon: 31.0,
        type: 'ecology',
        status: 'warning',
        value: 55,
        description: 'Засоление почв, эрозия береговой линии.',
        region: 'africa',
        level: 'object'
    },
    // MORE TREATMENT PLANTS
    {
        id: 't-04',
        name: 'Очистные сооружения Berlin (Германия)',
        lat: 52.52,
        lon: 13.41,
        type: 'treatment',
        status: 'normal',
        value: 96,
        description: 'Передовая система очистки с рекуперацией тепла.',
        region: 'europe',
        owner: 'Civilization Protocol Partner',
        level: 'object'
    },
    {
        id: 't-05',
        name: 'Станция опреснения Hadera (Израиль)',
        lat: 32.44,
        lon: 34.88,
        type: 'treatment',
        status: 'normal',
        value: 98,
        description: 'Крупнейшая станция обратного осмоса.',
        region: 'middle_east',
        level: 'object'
    },
    {
        id: 't-06',
        name: 'Changi NEWater (Сингапур)',
        lat: 1.38,
        lon: 104.0,
        type: 'treatment',
        status: 'normal',
        value: 99,
        description: 'Передовая система рециркуляции воды.',
        region: 'asia',
        owner: 'Civilization Protocol Partner',
        level: 'object'
    },
    // ADDITIONAL PUMPING STATIONS
    {
        id: 'p-04',
        name: 'Насосная станция Dubai',
        lat: 25.27,
        lon: 55.29,
        type: 'pumping',
        status: 'normal',
        value: 94,
        description: 'Современная система водоснабжения мегаполиса.',
        region: 'middle_east',
        level: 'object'
    },
    {
        id: 'p-05',
        name: 'Насосная станция São Paulo',
        lat: -23.55,
        lon: -46.63,
        type: 'pumping',
        status: 'warning',
        value: 68,
        description: 'Критическая инфраструктура, требуется модернизация.',
        region: 'americas',
        level: 'object'
    },
    {
        id: 'p-06',
        name: 'Насосная станция Ашхабад',
        lat: 37.95,
        lon: 58.38,
        type: 'pumping',
        status: 'warning',
        value: 62,
        description: 'Обеспечивает водоснабжение столицы.',
        region: 'central_asia',
        owner: 'VODPROM',
        level: 'object'
    }
];
